cutoff = 4.0
val_ratio = 0.1
dataset = '/home/energy/mahpe/Playground/Universal_FF/Dataset/Published/Combined.xyz'
#dataset = '/home/energy/mahpe/Playground/Universal_FF/Dataset/Published/NaMPO4_olivine_multiple.xyz'
max_steps = 1500000
batch_size = 20
initial_lr = 0.0001
forces_weight = 0.98
charge_weight = 0.1
stress_weight = 1000
log_interval = 2000

plateau_scheduler = true
normalization = true #false
atomwise_normalization = true #false
stop_patience = 1000

random_seed = 0
compute_forces = true
compute_stress = true
compute_magmom=true
compute_bader_charge=true
